repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.0
  hooks:
    - id: ruff-check
      args: ["--extend-select", "I", "--fix"]
    - id: ruff-format
      args: ["--exclude", "conftest.py"]