name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ruff without running check or format
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"

      - run: ruff check --extend-select I
      - run: ruff format --exclude conftest.py