name: Ruff

on:
  push:
    paths:
      - 'soe_vinorm/**'
      - 'tests/**'
      - '*.py'
      - 'pyproject.toml'
      - '.github/workflows/ruff.yml'
  pull_request:
    paths:
      - 'soe_vinorm/**'
      - 'tests/**'
      - '*.py'
      - 'pyproject.toml'
      - '.github/workflows/ruff.yml'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.19"
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync --dev

      - name: Run ruff check
        run: uv run ruff check --extend-select I

      - name: Run ruff format
        run: uv run ruff format --exclude conftest.py